name: Quicktill

on: [push, pull_request]

jobs:
  test:
    name: Test quicktill
    strategy:
      matrix:
        runs-on:
          - 'ubuntu-22.04'
          - 'ubuntu-24.04'
    runs-on: ${{ matrix.runs-on }}

    steps:
      - name: Check out project
        uses: actions/checkout@v4
      - name: Update OS package list
        run: |
          sudo apt-get update
      - name: Install OS-level dependencies
        run: |
          sudo apt-get install \
          flake8 \
          python3-pytest \
          python3-setuptools \
          python3-cryptography \
          python3-cups \
          python3-dateutil \
          python3-httplib2 \
          python3-odf \
          python3-psycopg2 \
          python3-qrcode \
          python3-reportlab \
          python3-requests \
          python3-requests-oauthlib \
          python3-sqlalchemy \
          python3-tomli
      - name: Lint with flake8
        run: |
          flake8 quicktill
      - name: Start postgresql
        run: |
          sudo systemctl start postgresql
          pg_lsclusters
      - name: Configure postgresql
        run: |
          sudo -u postgres createuser --echo -d $(whoami)
      - name: Test with pytest
        run: |
          pytest-3 quicktill
      - name: Run from command line
        run: |
          createdb testdb
          ./runtill -d dbname=testdb syncdb
          ./runtill -d dbname=testdb dbsetup examples/dbsetup.toml
          ./runtill -d dbname=testdb adduser "Test User" Test builtin:alice
          ./runtill -d dbname=testdb listusers
          ./runtill -d dbname=testdb totals
          ./runtill -d dbname=testdb flushdb
